name: baseline-scan
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    name: scanning app
    steps:
      - name: main page
        uses: actions/checkout@v2
      - name: ZAP Base Scan
        uses: zaproxy/action-baseline@v0.9.0