name: baseline-scan
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    name: scanning app
    steps:
      - name: Checkout Main Page
        uses: actions/checkout@v2
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'https://www.zaproxy.org/'